include:
  - otel/example/base/docker-compose.yaml

services:
  go-api-server:
    pid: host
    volumes:
      - /proc:/host/proc

  go-auto:
    depends_on:
      - go-api-server
    image: otel/autoinstrumentation-go:latest
    privileged: true
    pid: host
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_GO_AUTO_TARGET_EXE=/root/main
      - OTEL_SERVICE_NAME=go-api-server
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_GO_AUTO_GLOBAL=true
      - OTEL_GO_AUTO_INCLUDE_DB_STATEMENT=true
      - OTEL_GO_AUTO_PARSE_DB_STATEMENT=true
    volumes:
      - /proc:/host/proc
