# This file is created by reference from
# 1. https://github.com/jaegertracing/jaeger/tree/main/docker-compose/monitor
# 2. https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"

# version: "3.7"
services:
  # NOTE: change the service name if you copy-paste
  # Generate fake traces...
  # k6-tracing:
  #   image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
  #   environment:
  #     - ENDPOINT=otel_collector:4317
  #   restart: always
  #   depends_on:
  #     - otel_collector

  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:${TEMPO_TAG:-2.8.1}
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ../../data/tempo:/var/tempo

  tempo:
    image: *tempoImage
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ../../src/tempo/tempo-local.yaml:/etc/tempo.yaml
      - ../../data/tempo:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
      - "4318:4318" # otlp http
    depends_on:
      - init

  loki:
    image: grafana/loki:${LOKI_TAG:-3.5.1}
    restart: always
    ports:
      - 3100:3100/tcp
    volumes:
      - ../../src/loki/loki.yaml:/etc/loki/local-config.yaml
      - ../../data/loki:/loki

  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG:-v3.4.1}
    command:
      - --config.file=/etc/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-lifecycle
    volumes:
      - "../../src/prometheus/prometheus.yml:/etc/prometheus.yml"
      - "../../src/prometheus/targets.json:/etc/targets.json"
      - "../../data/prometheus:/prometheus"
      - ~/.aws:/home/.aws # for AWS credentials
    # environment:
    #   - AWS_ACCESS_KEY_ID
    #   - AWS_SECRET_ACCESS_KEY
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:${GRAFANA_TAG:-12.0.1}
    volumes:
      - ../../src/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../../src/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ../../src/grafana/dashboards/:/etc/grafana/provisioning/dashboards
      - ../../src/grafana/grafana-plugins:/var/lib/grafana/plugins
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      # - GF_FEATURE_TOGGLES_ENABLE=tempoSearch tempoBackendSearch tempoServiceGraph dashgpt
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary logsExploreTableVisualisation grafanaAdvisor
      - GF_INSTALL_PLUGINS=grafana-googlesheets-datasource,grafana-sentry-datasource,grafana-opensearch-datasource,grafana-athena-datasource,grafana-amazonprometheus-datasource,grafana-synthetic-monitoring-app,grafana-lokiexplore-app,grafana-metricsdrilldown-app,grafana-pyroscope-app,grafana-exploretraces-app,grafana-investigations-app,grafana-resourcesexporter-app,grafana-advisor-app,grafana-llm-app
    ports:
      - 3000:3000
