{
 "title": "Analytics Info",
 "tags": [
  "Backend",
  "Common"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ApplicationPrometheus", "label": "ApplicationPrometheus", "query": "prometheus" },
   {
    "name": "Component",
    "query": {
     "query": "label_values(ubqt_http_requests_total,job)"
    }
   },
   { "name": "Quantile", "label": "Quantile", "query": "0.5,0.75,0.8,0.9,0.95,0.99" },
   { "name": "interval", "label": "interval", "query": "2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "$Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(status) (irate(ubqt_http_requests_total{job=~\"$Component\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(url) (irate(api_request_total{job=~\"$Component\", url=\"/*path\"}[1m]))",
     "legendFormat": "api_request_total: {{url}}"
    }
   ]
  },
  {
   "title": "Synthetic Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "column": "ingested_time",
     "connectionArgs": {
      "catalog": "__default",
      "database": "__default",
      "region": "__default",
      "resultReuseEnabled": false,
      "resultReuseMaxAgeInMinutes": 60
     },
     "rawSQL": "SELECT \ndate_trunc('minute', ingested_time) as time,\ncount(*) as \"synthetic_count\"\nFROM $__table() \nWHERE \n$__timeFilter(ingested_time) \nand date_parse(day,'%Y/%m/%d')\nBETWEEN date '${__from:date:YYYY-MM-DD}' - interval '1' day \nAND date '${__to:date:YYYY-MM-DD}' + interval '1' day\nGroup By 1",
     "table": "unifi_cap_device_test_synthetic_raw"
    }
   ]
  },
  {
   "title": "Processed batches/sec (by namespace/type)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace, type) (irate(process_total{job=~\"$Component\"}[1m]))",
     "legendFormat": "{{namespace}} | {{type}}",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Put kinesis record error RPS (by namespace/type)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace, type) (irate(put_record_err_total{job=~\"$Component\"}[1m]))",
     "legendFormat": "{{namespace}} | {{type}}",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Unknown namespace/type RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace, type) (irate(unknown_namespace_type_total{job=~\"$Component\"}[1m]))",
     "legendFormat": "{{namespace}} | {{type}}",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "json marshal error count/sec (by namespace/type)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(namespace, type) (irate(json_marshal_err_total{job=~\"$Component\"}[1m]))",
     "legendFormat": "{{namespace}} | {{type}}",
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  }
 ]
}