{
 "title": "Go Processes",
 "tags": [
  "Backend",
  "Common",
  "Go"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "Component", "query": { "query": "label_values(go_info,job)" } },
   { "name": "AggregationLabel", "label": "AggregationLabel", "query": "job,instance" },
   {
    "name": "AggregationItem",
    "query": {
     "query": "label_values(go_info,$AggregationLabel)"
    }
   },
   { "name": "interval", "query": "2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage (in $interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}[$interval])) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}}"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | resident"
    },
    {
     "expr": "sum(process_virtual_memory_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | virtual"
    }
   ]
  },
  {
   "title": "GC Duration Mean (in $interval)",
   "type": "graph",
   "description": "go_gc_duration_seconds_sum / go_gc_duration_seconds_count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}[$interval])) by ($AggregationLabel, endpoint) / sum(rate(go_gc_duration_seconds_count{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}[$interval])) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}}"
    }
   ]
  },
  {
   "title": "GC Duration Quantiles (0.75 quantile)",
   "type": "timeseries",
   "description": "A summary of the pause duration of garbage collection cycles.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"^($Component).*\", quantile=\"0.75\"}",
     "legendFormat": "{{$AggregationLabel}} | {{quantile}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Number of goroutines that currently exist.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of OS threads created.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_threads{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}}"
    }
   ]
  },
  {
   "title": "Memory Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory in Off-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_mspan_inuse_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | inuse"
    },
    {
     "expr": "sum(go_memstats_mspan_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | sys"
    },
    {
     "expr": "sum(go_memstats_mcache_inuse_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | mcache_inuse"
    },
    {
     "expr": "sum(go_memstats_mcache_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | mcache_sys"
    },
    {
     "expr": "sum(go_memstats_buck_hash_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | buck_hash"
    },
    {
     "expr": "sum(go_memstats_gc_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | gc_sys"
    },
    {
     "expr": "sum(go_memstats_other_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "bytes of memory are used for other runtime allocations {instance={{$AggregationLabel}}}"
    },
    {
     "expr": "sum(go_memstats_next_gc_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | next_gc"
    }
   ]
  },
  {
   "title": "Memory in Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_heap_alloc"
    },
    {
     "expr": "sum(go_memstats_heap_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_heap_sys"
    },
    {
     "expr": "sum(go_memstats_heap_idle_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_idle_sys"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_inuse_sys"
    },
    {
     "expr": "sum(go_memstats_heap_released_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_heap_released"
    }
   ]
  },
  {
   "title": "Memory in Stack",
   "type": "timeseries",
   "description": "stack_inuse: Number of bytes in use by the stack allocator.\nstack_sys: Number of bytes obtained from system for stack allocator.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | stack_inuse"
    },
    {
     "expr": "sum(go_memstats_stack_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | stack_sys"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "timeseries",
   "description": "Number of bytes obtained from system.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_sys"
    }
   ]
  },
  {
   "title": "Rates of Allocation (in $interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_alloc_bytes_total{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}[$interval])) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_alloc_bytes_total"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Total number of mallocs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_memstats_mallocs_total{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint) - sum(go_memstats_frees_total{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_mallocs - memstats_frees"
    }
   ]
  },
  {
   "title": "Rate of Objects Allocated (in $interval)",
   "type": "timeseries",
   "description": "shows how many heap objects are allocated. This is a counter value so you can use rate() to objects allocated/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_mallocs_total{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}[$interval])) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}} | memstats_mallocs_total"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences (in $interval)",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_lookups_total{job=~\"^($Component).*\", $AggregationLabel=~\"$AggregationItem\"}[$interval])) by ($AggregationLabel, endpoint)",
     "legendFormat": "{{$AggregationLabel}}"
    }
   ]
  }
 ]
}