{
 "title": "Pond Pool Info",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "AggregationLabel", "query": { "query": "label_names()" } },
   {
    "name": "AggregationItem",
    "query": {
     "query": "label_values($AggregationLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool workers running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pool_workers_running{$AggregationLabel=~\"$AggregationItem\"}"
    }
   ]
  },
  {
   "title": "Pool workers idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pool_workers_idle{$AggregationLabel=~\"$AggregationItem\"}"
    }
   ]
  },
  {
   "title": "Pool tasks submitted rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by($AggregationLabel) (irate(pool_tasks_submitted_total{$AggregationLabel=~\"$AggregationItem\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pool tasks completed rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by($AggregationLabel) (irate(pool_tasks_completed_total{$AggregationLabel=~\"$AggregationItem\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pool tasks failed rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by($AggregationLabel) (irate(pool_tasks_failed_total{$AggregationLabel=~\"$AggregationItem\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pool tasks successful rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by($AggregationLabel) (irate(pool_tasks_successful_total{$AggregationLabel=~\"$AggregationItem\"}[1m]))"
    }
   ]
  }
 ]
}