{
 "title": "RED Method",
 "tags": [
  "Backend",
  "Common"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "SystemPrometheus", "label": "SystemPrometheus", "query": "prometheus" },
   { "name": "ApplicationPrometheus", "label": "ApplicationPrometheus", "query": "prometheus" },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{}, namespace)"
    }
   },
   {
    "name": "Component",
    "query": {
     "query": "label_values(go_info{namespace=~\"$Namespace\"}, job)"
    }
   },
   { "name": "Quantile", "label": "Quantile", "query": "0.5,0.75,0.8,0.9,0.95,0.99" },
   { "name": "interval", "label": "interval", "query": "2m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "$Component", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (irate(ubqt_http_requests_total{namespace=~\"^($Namespace)$\", job=~\"$Component\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Time in $interval",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.8, sum(irate(ubqt_http_duration_seconds_bucket{namespace=~\"^($Namespace)$\", job=~\"$Component\"}[$interval])) by (namespace,le))",
     "legendFormat": "Latency in 0.8 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(ubqt_http_duration_seconds_bucket{namespace=~\"^($Namespace)$\", job=~\"$Component\"}[$interval])) by (namespace,le))",
     "legendFormat": "Latency in 0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(ubqt_http_duration_seconds_bucket{namespace=~\"^($Namespace)$\", job=~\"$Component\"}[$interval])) by (namespace,le))",
     "legendFormat": "Latency in 0.99 quantile"
    }
   ]
  },
  {
   "title": "Request Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(ubqt_http_request_bytes_sum{namespace=~\"^($Namespace)$\", job=~\"$Component\"}[$interval]))*8\n",
     "legendFormat": "{{job}}_In"
    }
   ]
  },
  {
   "title": "Response traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (job) (irate(ubqt_http_response_bytes_sum{namespace=~\"^($Namespace)$\", job=~\"$Component\"}[$interval]))*8",
     "legendFormat": "{{job}}_Out"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (status) (irate(ubqt_http_requests_total{namespace=~\"^($Namespace)$\"}[$interval]))",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Response Time Quantile in $interval (overall)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.8, sum(irate(ubqt_http_duration_seconds_bucket{namespace=~\"^($Namespace)$\"}[$interval])) by (namespace,le))",
       "legendFormat": "Latency in 0.8 quantile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(ubqt_http_duration_seconds_bucket{namespace=~\"^($Namespace)$\"}[$interval])) by (namespace,le))",
       "legendFormat": "Latency in 0.95 quantile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(ubqt_http_duration_seconds_bucket{namespace=~\"^($Namespace)$\"}[$interval])) by (namespace,le))",
       "legendFormat": "Latency in 0.99 quantile"
      }
     ]
    },
    {
     "title": "Request & Response traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum(irate(ubqt_http_request_bytes_sum{namespace=~\"^($Namespace)$\"}[$interval]))*8\n",
       "legendFormat": "In"
      },
      {
       "expr": "sum(irate(ubqt_http_response_bytes_sum{namespace=~\"^($Namespace)$\"}[$interval]))*8\n",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Request Traffic",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (job) (irate(ubqt_http_request_bytes_sum{namespace=~\"^($Namespace)$\"}[$interval]))*8\n",
       "legendFormat": "{{job}}_In"
      }
     ]
    },
    {
     "title": "Response traffic",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (job) (irate(ubqt_http_response_bytes_sum{namespace=~\"^($Namespace)$\"}[$interval]))*8",
       "legendFormat": "{{job}}_Out"
      }
     ]
    }
   ]
  }
 ]
}